spring:
  application:
    name: mongotest

server:
  port: 8080

service:
  datakick:
    url: https://www.datakick.org/api/items

management:
  endpoint:
    health:
      show-details: always

  health:
    mongo:
      enabled: true
